
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres

development:
  <<: *default
  database: formsApi_development


test:
  <<: *default
  database: formsApi_test

production:
  <<: *default
  database: formsApi_production
